# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slv < Formula
  desc ""
  homepage "https://github.com/amagimedia/slv"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.9.3/slv-beta_0.9.3_darwin_arm64.zip"
      sha256 "588dbc7d89a0932137113e76d340729bb5d140957dc234fabd4cc63eec2eb10b"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.9.3/slv-beta_0.9.3_darwin_amd64.zip"
      sha256 "56bd4af3d1ceb7d1e4b5946a8d73c15950ebc3c8a5bf5091e1233d9fa15c616b"

      def install
        bin.install "slv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.9.3/slv-beta_0.9.3_linux_arm64.zip"
      sha256 "4aebc2c3ee56ed9636958b7445a3a3c01fee0e1fe6b87b0cc0af9f10afc47fd0"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.9.3/slv-beta_0.9.3_linux_amd64.zip"
      sha256 "791850c3d1d72ba2ede5f5c73f1d0fa762f48d09344ef7a7dc3e15bfb54e8f1f"

      def install
        bin.install "slv"
      end
    end
  end
end
