# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slv < Formula
  desc ""
  homepage "https://github.com/amagimedia/slv"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.10.0/slv-beta_0.10.0_darwin_amd64.zip"
      sha256 "869e50eba544520a64857d962844a1ec53292112955ddec1079ef14b5f944d37"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.10.0/slv-beta_0.10.0_darwin_arm64.zip"
      sha256 "42040dbb824eb0c33a15c199eea49dd4753f546b913074d240921e8544c9586f"

      def install
        bin.install "slv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.10.0/slv-beta_0.10.0_linux_arm64.zip"
      sha256 "0f9260c290b85ae6af670ee501bc9fac6e049272ab9ff7b366413f7866b2e305"

      def install
        bin.install "slv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amagimedia/slv-beta/releases/download/v0.10.0/slv-beta_0.10.0_linux_amd64.zip"
      sha256 "d496fee60abf1c06aecb46319bc967a7addf4d31ac40ba2fe52bbb0152256f0d"

      def install
        bin.install "slv"
      end
    end
  end
end
